"""Streamlit entrypoint. Top tabs for nav - four views on one dataset don't
need permanent sidebar chrome, a tab bar communicates the same four
destinations with less screen real estate spent on navigation. One slim
header row above the tabs shows brand + live status (batch, production
version, rollback-reference health), fetched once per load, visible
regardless of which tab is active.

Theme comes from dashboard/styles.css. .streamlit/config.toml pins the base
Streamlit theme to light so it can't fall back to a dark variant on a
client machine.
"""

import base64
import sys
from pathlib import Path

import streamlit as st

# streamlit run dashboard/app.py puts dashboard/ itself on sys.path, not the
# repo root, so `from src...` / `from dashboard...` below would fail. Insert
# the repo root explicitly, before any of those imports.
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from dashboard.views import audit_log, drift, lineage, overview  # noqa: E402
from src.db.connection import get_engine  # noqa: E402
from src.db.repository import get_latest_champion, get_pipeline_state  # noqa: E402

# Icon lives at the repo root's assets/ folder, not under dashboard/ - it's
# provided by whoever deploys this, not generated by the app. Discovered by
# extension rather than a hardcoded filename, so this doesn't break if the
# file isn't named exactly "logo.png".
ASSETS_DIR = REPO_ROOT / "assets"
_MIME_BY_SUFFIX = {".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".ico": "image/x-icon"}


def _find_icon() -> Path | None:
    if not ASSETS_DIR.exists():
        return None
    for ext in ("*.svg", "*.png", "*.jpg", "*.jpeg", "*.ico"):
        matches = sorted(ASSETS_DIR.glob(ext))
        if matches:
            return matches[0]
    return None


ICON_PATH = _find_icon()

st.set_page_config(
    page_title="Credit Risk Governance",
    # Streamlit reads this file itself (server-side), so a real path works
    # here even though it can't be used directly in an <img src> below.
    page_icon=str(ICON_PATH) if ICON_PATH else ":bar_chart:",
    layout="wide",
    initial_sidebar_state="collapsed",
)


@st.cache_resource
def load_css() -> str:
    return (Path(__file__).parent / "styles.css").read_text()


@st.cache_resource
def load_brand_mark_html() -> str:
    """HTML for the in-header brand mark, built from whatever icon file is
    at assets/. SVG is inlined directly (crisp at any size, no encoding
    needed). Raster formats are base64-embedded as a data URI, since the
    browser can't resolve a local filesystem path in an <img src="...">
    the way Streamlit's own page_icon (read server-side) can. Falls back to
    a plain text mark if no icon file is present.
    """
    if ICON_PATH is None:
        return '<div class="crg-brand-mark crg-brand-mark-fallback">CRG</div>'
    if ICON_PATH.suffix == ".svg":
        return f'<div class="crg-brand-mark">{ICON_PATH.read_text()}</div>'
    mime = _MIME_BY_SUFFIX.get(ICON_PATH.suffix, "image/png")
    encoded = base64.b64encode(ICON_PATH.read_bytes()).decode("ascii")
    return f'<div class="crg-brand-mark"><img src="data:{mime};base64,{encoded}" alt="logo"/></div>'


st.markdown(f"<style>{load_css()}</style>", unsafe_allow_html=True)

engine = get_engine()

with engine.connect() as conn:
    state = get_pipeline_state(conn)
    champion = get_latest_champion(conn)

version_label = f'v{champion["model_version"]}' if champion else "none"
reference_stale = bool(champion and champion.get("reference_stale"))
dot_class = "warn" if reference_stale else ""
reference_label = "stale" if reference_stale else "fresh"

st.markdown(
    '<div class="crg-topbar">'
    f'<div class="crg-brand">{load_brand_mark_html()}'
    "<div>"
    '<div class="crg-brand-title">Credit Risk Governance</div>'
    '<div class="crg-brand-subtitle">Autonomous retrain, promote, and rollback pipeline</div>'
    "</div>"
    "</div>"
    '<div class="crg-status-strip">'
    '<div class="crg-status-item">'
    '<span class="crg-status-label">Batch</span>'
    f'<span class="crg-status-value">{state["current_batch"]}</span>'
    "</div>"
    '<div class="crg-status-item">'
    '<span class="crg-status-label">Production</span>'
    f'<span class="crg-status-value">{version_label}</span>'
    "</div>"
    '<div class="crg-status-item">'
    '<span class="crg-status-label">Reference</span>'
    f'<span class="crg-status-value"><span class="crg-dot {dot_class}"></span>&nbsp;{reference_label}</span>'
    "</div>"
    "</div>"
    "</div>",
    unsafe_allow_html=True,
)

tab_overview, tab_lineage, tab_drift, tab_audit = st.tabs(
    ["Overview", "Lineage", "Drift", "Audit Log"]
)

with tab_overview:
    overview.render(engine)

with tab_lineage:
    lineage.render(engine)

with tab_drift:
    drift.render(engine)

with tab_audit:
    audit_log.render(engine)